title: "Your Name"
description: "Particle Physicist | Data Scientist | Machine Learning Engineer"
url: ""
baseurl: ""
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
